version: "3"

services:
  redis:
    image: redis:4-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./docker:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    ports:
      - 5601:5601

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.6.2
  #   container_name: logstash
  #   volumes:
  #     - ./:/logstash_dir
  #   command: logstash -f /logstash_dir/logstash.conf
  #   ports:
  #     - "9600:9600"

volumes:
  es_data:
